#!/bin/sh

##############################################################################
# chkconfig: 345 90 10
# description: Solr
##############################################################################
# This is the startup script for Solr , running under linuxes
# with chkconfig support.
#
##############################################################################

##############################################################################
# Change these to match your environment. In particular, change SOLR_HOME
# and SOLR_RUNASUSER
JETTY_PORT=8983

SOLR_HOME=/home/solr/solr_config
SOLR_SERVER_DIR=/home/solr/solr
SOLR_RUNASUSER=solr

##############################################################################

##############################################################################
# It should normally not be necessary to change below this line
##############################################################################
THIS=$0

#JAVA_OPTS="-Xmx2048m -XX:MaxPermSize=128m"
CMD="${SOLR_SERVER_DIR}/bin/solr"

if [ $(whoami) == root ]; then
    echo Switching from root to $SOLR_RUNASUSER: su $SOLR_RUNASUSER -c "${THIS} $*"
    su $SOLR_RUNASUSER -c "${THIS} $*"
    exit
fi

if [ $(whoami) != $SOLR_RUNASUSER ]; then
    echo You are currently logged in as user $(whoami).
    echo This script must be run as either '${SOLR_RUNASUSER}' or 'root'.
    exit
fi


start() {
    echo "Starting Solr"
    ps -ef | grep "\-Djetty.port=${JETTY_PORT}" | grep -v grep
    if [ "$?" = "0" ]; then
      echo "Solr is already running"
      exit 1
    else
      (cd $SOLR_SERVER_DIR ; ${CMD} -p ${JETTY_PORT} start)
    fi   
}

stop() {
    echo "Stopping ${SOLR_NAME}"
    (cd $SOLR_SERVER_DIR ; ${CMD} stop -all)
}

status() {
    echo "Searching for ${SOLR_NAME}"
    (cd $SOLR_SERVER_DIR ; ${CMD} -i)
}

case "$1" in

    start)
        start
        ;;

    stop)
	stop
        ;;

    restart)
	stop
	sleep 5
	start
        ;;

    status)
	status
        ;;

    *)
        echo "Usage: $0 (start|stop|restart|status)"
        exit 2

esac

exit $?
