#!/bin/sh

##############################################################################
# chkconfig: 345 90 10
# description: Solr
##############################################################################
# This is the startup script for Solr , running under linuxes
# with chkconfig support.
#
##############################################################################

##############################################################################
# Change these to match your environment. In particular, change SOLR_HOME
# and SOLR_RUNASUSER

JETTY_PORT=8983
JETTY_STOP_PORT=8884
JETTY_STOP_KEY="34t6adfsgertt435po34"

SOLR_NAME=solr
SOLR_HOME=/home/vagrant/solr_home
SOLR_SERVER_DIR=/home/vagrant/solr/example
SOLR_INSTANCE_DIR=/home/vagrant/solr
SOLR_RUNASUSER=vagrant

##############################################################################

##############################################################################
# It should normally not be necessary to change below this line
##############################################################################
THIS=$0

JAVA_OPTS="-DSTOP.PORT=${JETTY_STOP_PORT} -DSTOP.KEY=${JETTY_STOP_KEY} -Djetty.port=${JETTY_PORT} -Xmx2048m -XX:MaxPermSize=128m -Dsolr.solr.home=${SOLR_HOME} -Dsolr.install.dir=${SOLR_INSTANCE_DIR}"

CMD="java ${JAVA_OPTS} -jar start.jar"

if [ $(whoami) == root ]; then
    echo Switching from root to $SOLR_RUNASUSER: su $SOLR_RUNASUSER -c "${THIS} $*"
    su $SOLR_RUNASUSER -c "${THIS} $*"
    exit
fi

if [ $(whoami) != $SOLR_RUNASUSER ]; then
    echo You are currently logged in as user $(whoami).
    echo This script must be run as either '${SOLR_RUNASUSER}' or 'root'.
    exit
fi


start() {
    echo "Starting ${SOLR_NAME}"
    ps -ef | grep "\-Djetty.port=${JETTY_PORT}" | grep -v grep
    if [ "$?" = "0" ]; then
      echo "${SOLR_NAME} is already running"
      exit 1
    else
      (cd $SOLR_SERVER_DIR ; $CMD >logs/$SOLR_NAME-stdout.log 2>logs/$SOLR_NAME-stderr.log &)
    fi   
}

stop() {
    echo "Stopping ${SOLR_NAME}"
    (cd $SOLR_SERVER_DIR ; $CMD --stop)
}

status() {
    echo "Searching for ${SOLR_NAME}"
    ps -ef | grep "\-Djetty.port=${JETTY_PORT}" | grep -v grep
    if [ "$?" = "0" ]; then
      echo "${SOLR_NAME} is running"
    else
      echo "${SOLR_NAME} is not running"
      exit 1
    fi
}

case "$1" in

    start)
        start
        ;;

    stop)
	stop
        ;;

    restart)

	stop
	sleep 5
	start
        ;;

    status)
	status
        ;;

    *)
        echo "Usage: $0 (start|stop|restart|status)"
        exit 2

esac

exit $?
